Sys.setlocale("LC_TIME","English_United States.1252")
data <- read.table('household_power_consumption.txt', header=TRUE, sep=';', stringsAsFactors = FALSE, na.strings = '?', comment.char="", nrow = 100000)
d <- as.Date(data$Date, format = '%d/%m/%Y')
d1 <- as.Date('2007-02-01')
d2 <- as.Date('2007-02-02')
data <- data[d >= d1 & d <= d2,]
data$datetime <- strptime(paste(data$Date, data$Time), format = '%d/%m/%Y %H:%M:%S')
png('plot4.png', bg = "transparent")
par(mfrow = c(2,2))
plot(data$datetime, data$Global_active_power, type = 'l', xlab = '', ylab = 'Global Active Power')
plot(data$datetime, data$Voltage, type = 'l', xlab = 'datetime', ylab = 'Voltage')
plot(data$datetime, data$Sub_metering_1, type = 'l', xlab = '', ylab = 'Energy sub metering')
lines(data$datetime, data$Sub_metering_2, col = 'red')
lines(data$datetime, data$Sub_metering_3, col = 'blue')
legend('topright', lty = 'solid', col = c('black', 'red', 'blue'), legend = c('Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3'), bty = 'n')
plot(data$datetime, data$Global_reactive_power, type = 'l', xlab = 'datetime', ylab = 'Global_reactive_power')
dev.off()
